# This is a basic workflow to help you get started with Actions

name: JackWebber

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
   schedule:
      - cron: "*/20 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update GitHub Profile README
        uses: LawrenceBaatjies/github-update-readme@master
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         header: "Hey, I'm Ryan! 👋"
         subhead: "Currently a student in Singapore, passionate about creating all-things-tech to improve society."
         footer: "**Learn more about me at [ryanthe.com](https://www.ryanthe.com)!**"  
         excludeActivity: '["WatchEvent"]'
         excludeRepo: '["LawrenceBaatjies/LawrenceBaatjies"]'
